export type SitRep = {
  id: string;
  title: string;
  date: string;
  spiId: string;
  update: string;
  challenges: string;
  nextSteps: string;
  status: 'pending-review' | 'ready' | 'submitted';
  level: 'CEO' | 'SVP' | 'CTO';
  summary: string;
  projectId?: string;
  departmentId: string;
  fortune30PartnerId?: string;
  smePartnerId?: string;
  teams?: string[];
  pointsOfContact?: string[];
  poc?: string;
  pocDepartment?: string;
  ratMember: string;
};